using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.PersonalEconomy.Components;
using Content.Shared.Hands.Components;
using Content.Shared.Hands.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.PersonalEconomy.UI.POS;

[GenerateTypedNameReferences]
public sealed partial class PoSMenu : FancyWindow
{
    [Dependency] private readonly IPlayerManager _playerMan = null!;
    [Dependency] private readonly IEntityManager _entityManager = null!;

    public Action<string>? OnNumberEntered;
    public Action? OnClearButtonPressed;

    // when locked, the merchant view is hidden behind a PIN and we don't auto-present held cards
    public bool LockMode;

    private bool _accountOpen;
    private PoSLockBox? _lockBox;
    private bool _lockClaimed;

    public PoSMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CreateInvalidSetupBox();

        UIKeypad.OnEnterButtonPressed += s => OnNumberEntered?.Invoke(s);
        UIKeypad.OnClearButtonPressed += () => OnClearButtonPressed?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        CheckForCard();
        UpdateLockState();
    }

    //an unclaimed terminal can only be claimed with a card in hand, so swap the prompt & keypad based on what's held
    private void UpdateLockState()
    {
        if (!LockMode || _lockBox is null)
            return;

        var hasCard = false;
        if (_playerMan.LocalEntity is { } realEnt && _entityManager.HasComponent<HandsComponent>(realEnt))
        {
            var handSystem = _entityManager.System<SharedHandsSystem>();
            foreach (var ent in handSystem.EnumerateHeld(realEnt))
            {
                if (!_entityManager.HasComponent<BankCardComponent>(ent))
                    continue;

                hasCard = true;
                break;
            }
        }

        //already claimed -> just need the owner's PIN; unclaimed -> need a card to claim
        var needsCard = !_lockClaimed && !hasCard;
        KeypadContainer.Visible = !needsCard;
        _lockBox.SetNeedsCard(needsCard);
    }

    private void CheckForCard()
    {
        //if we're entering a PIN, we've already got an open account, we are the server or the player entity does not have hands, return
        if (LockMode || _accountOpen || _playerMan.LocalEntity is not { } realEnt || !_entityManager.HasComponent<HandsComponent>(realEnt))
        {
            return;
        }

        //go over everything that's held by the player
        var handSystem = _entityManager.System<SharedHandsSystem>();
        var held = handSystem.EnumerateHeld(realEnt);
        foreach (var ent in held)
        {
            //if it's not a bank card, continue
            if (!_entityManager.TryGetComponent<BankCardComponent>(ent, out var comp))
                continue;

            //set the entered number & invoke the number entered action
            UIKeypad.SetEnteredNumber($"{comp.AccountNumber.Number:000000}");
            OnNumberEntered?.Invoke($"{comp.AccountNumber.Number:000000}");
            break;
        }
    }

    public void ClearBox()
    {
        MainContainer.RemoveAllChildren();
        _accountOpen = false;
        LockMode = false;
        _lockBox = null;
    }

    public PoSLockBox CreateLockBox(bool claimed)
    {
        ClearBox();
        var box = new PoSLockBox();
        MainContainer.AddChild(box);
        LockMode = true;
        _lockBox = box;
        _lockClaimed = claimed;
        //the merchant types their PIN on the keypad, same as the concept; UpdateLockState handles the present-card case
        UpdateLockState();
        return box;
    }

    public PoSSetupBox CreateSetupBox()
    {
        ClearBox();
        var box = new PoSSetupBox(true);
        MainContainer.AddChild(box);
        _accountOpen = true;
        KeypadContainer.Visible = false;
        return box;
    }

    public PoSSetupBox CreateInvalidSetupBox()
    {
        ClearBox();
        var box = new PoSSetupBox(false);
        MainContainer.AddChild(box);
        KeypadContainer.Visible = false;
        return box;
    }

    public PoSPaymentBox CreatePaymentBox()
    {
        ClearBox();
        var box = new PoSPaymentBox(true);
        MainContainer.AddChild(box);
        _accountOpen = true;
        //the review screen has nothing to type, so drop the keypad
        KeypadContainer.Visible = false;
        return box;
    }

    public PoSPaymentBox CreateInvalidPaymentBox()
    {
        ClearBox();
        var box = new PoSPaymentBox(false);
        MainContainer.AddChild(box);
        //the customer types their account number here (or presents a card)
        KeypadContainer.Visible = true;
        return box;
    }
}

