using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class ATMMenu : FancyWindow
{
    public Action? OnTransactionButtonPressed;
    public Action? OnInsertCardPressed;
    public Action? OnEjectCardPressed;

    public Func<Entity<BankAccountComponent>?>? GetInsertedAccount;

    private EntityUid? _shownAccount;

    public ATMMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CreateInvalidInfoBox();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        var inserted = GetInsertedAccount?.Invoke();

        if (inserted == null)
        {
            if (_shownAccount != null)
                CreateInvalidInfoBox();
            return;
        }

        if (_shownAccount == inserted.Value.Owner)
            return;

        CreateInfoBoxForAccount(inserted.Value);
    }

    public void CreateInvalidInfoBox()
    {
        ClearInfoBox();

        var infoBox = new NoAccountInfoBox();
        infoBox.OnInsertCardPressed += () => OnInsertCardPressed?.Invoke();
        AccountInfoContainer.AddChild(infoBox);
    }

    public void CreateInfoBoxForAccount(Entity<BankAccountComponent> account)
    {
        ClearInfoBox();

        var infobox = new AccountInfoBox(account);
        infobox.OnTransactionButtonPressed += () => OnTransactionButtonPressed?.Invoke();
        infobox.OnEjectPressed += () => OnEjectCardPressed?.Invoke();
        AccountInfoContainer.AddChild(infobox);
        _shownAccount = account.Owner;
    }

    public void ClearInfoBox()
    {
        AccountInfoContainer.RemoveAllChildren();
        _shownAccount = null;
    }
}
