using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class NoAccountInfoBox : BoxContainer
{
    public Action? OnInsertCardPressed;

    public NoAccountInfoBox()
    {
        RobustXamlLoader.Load(this);

        InsertCardButton.OnPressed += _ => OnInsertCardPressed?.Invoke();
    }
}
